# Generated by Django 5.0.4 on 2024-06-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartsApp', '0001_initial'),
        ('StoreApp', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='StoreApp.variation'),
        ),
    ]
